[package]
name = "fuzzy_cognitive_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
diesel = { version = "2.0.0", features = ["postgres", "serde_json"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
dotenvy = "0.15.6"
